name: server_shelf
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.7 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {dio: ^4.0.6, http: ^0.13.5, mysql1: ^0.20.0, mysql_client: ^0.0.27, shelf_router: ^1.1.2
}
